### ISSUE TITLE
Decide on a branching model?

### ISSUE THREAD

**Issue by Megalomaniak** [TwistedTwigleg/vanilla-bootstrap#3]
Perhaps something like what is described here:
https://nvie.com/posts/a-successful-git-branching-model/

Though I do thing it's not too pressing yet, it is probably good to start thinking about it.

**Comment by TwistedTwigleg** [comment]
While I agree the issue is not too pressing right now, it is definitely something to be thinking about. As the theme gets bigger and more complex, having a defined branching model would certainly make things better.

I think the model described in the link above would work. Ultimately, we'd just need to find a model and try to do our best to stick to it.

Using a branching model like described in the article would also make it easier to know when to update the theme on the server, as we'd just update every time we decide on a release.

**Comment by Megalomaniak** [comment]
I think for now we have something that works so this can be closed.
